language: generic
sudo: required
services:
  - docker

after_success:
  - docker build -t vishalsumant/multi-client  ./client
  - docker build -t vishalsumant/multi-nginx  ./nginx
  - docker build -t vishalsumant/multi-server  ./server
  - docker build -t vishalsumant/multi-worker  ./worker


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  - docker push vishalsumant/multi-client
  - docker push vishalsumant/multi-nginx
  - docker push vishalsumant/multi-server
  - docker push vishalsumant/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-436408651451
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




