language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vishalsumant/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vishalsumant/react-test npm test




